package tools

import "golang.org/x/exp/rand"

var Msgs = []string{
	"讲一个10个字左右的冷笑话",
	"翻译一下：I love you",
	"给我讲一个笑话",
	"讲一个故事",
	"给我讲一个童话故事",
	"你可以阅读文件吗？",
	"常见的排序算法有哪洗？",
	"给我讲一个关于爱情的故事",
	"来一个简短的幽默小段子",
	"请把'I love you'翻译成中文",
	"分享一则轻松的笑话",
	"叙述一个有趣的故事",
	"讲述一个梦幻般的童话",
	"你能否处理文档内容？",
	"列举一些基础的排序方法",
	"描述一段浪漫的情缘故事",
	"请讲一个不超过十个字的冷笑话",
	"把'我爱你'用其他语言怎么表达？",
	"来一段简短的幽默小品",
	"叙述一个引人入胜的故事",
	"讲述一个充满想象的童话",
	"你支持文档阅读功能吗？",
	"列举几种常用的排序算法",
	"分享一个关于爱情的动人故事",
	"简短的冷笑话来一个",
	"'I love you'用中文怎么说？",
	"简短笑话一则",
	"讲述一个故事，让人会心一笑",
	"童话故事时间到了",
	"你能否阅读并理解文件？",
	"介绍几种排序算法",
	"讲述一个关于爱与被爱的故事",
	"Can you tell a joke in under ten words?",
	"How do you say 'I love you' in Spanish?",
	"Share a quick-witted joke, please.",
	"Narrate a story that makes me smile.",
	"Tell me a fable that sparks the imagination.",
	"Are you capable of processing documents?",
	"Name a few fundamental sorting algorithms.",
	"Spin a tale of love that touches the heart.",
	"Got any pithy jokes up your sleeve?",
	"Could you translate 'I love you' into another language?",
	"Care to share a brief comedic sketch?",
	"Tell a story that's sure to entertain.",
	"Let's hear a fairy tale full of enchantment.",
	"Do you have the ability to read and comprehend files?",
	"List some common sorting techniques.",
	"Tell a story of romance that resonates.",
	"A short, snappy joke, if you please.",
	"In what other languages can you express 'I love you'?",
	"Let's have a concise joke to lighten the mood.",
	"Share a narrative that brings a chuckle.",
	"A story that captivates, please.",
	"A fairy tale to spark the imagination.",
	"Is document reading within your capabilities?",
	"Enumerate some basic sorting methods.",
	"Tell a story of love that stirs the soul.",
	"How about a joke that's concise and cool?",
	"'I love you' in French, s'il vous plaît?",
	"A joke that's short and sweet.",
	"Tell a story that's a real crowd-pleaser.",
	"A tale of enchantment from the world of fairies.",
	"Can you handle reading through documents?",
	"Can you list off a couple of sorting algorithms?",
	"Share a story of love that's truly magical.",
}

func GetRandMsg() string {
	length := len(Msgs)
	return Msgs[rand.Intn(length)]
}
