syntax: 1.0
model_mapping:
  gpt-4o-mini: # 无须增加gpt-4o-mini到gpt-4o-mini本身的映射，程序会自动添加
    - gpt-4o-mini-xxxx
    - gpt-4o-mini-yyyy
  deepseek-chat:
    - "deepseek-ai/DeepSeek-V2.5"
  deepseek-coder:
    - "deepseek-ai/DeepSeek-V2.5"
  gemini_model1:
    - gemini_model1_provider1
    - gemini_model1_provider2
check_models: #需要定时检测的模型，传入第三方调用的模型名称
  - "gpt-4o-mini"
  - "deepseek-chat"
  - "deepseek-coder"
providers:
  - provider: openai  # "openai"  "siliconflow" "openaiCompatible"
    data:
      - name: provider1
        url: https://api.provider1.com
        models:
          - model1_provider1
          - model2_provider1
        api_keys:
          - your_api_key_here
          - your_api_key_here_2
      - name: provider1
        url: https://api.provider1.com
        models:
          - model1_provider1
          - model2_provider1
        api_keys:
          - your_api_key_here
          - your_api_key_here_2
  - provider: openaiCompatible  # "openai"  "siliconflow" "openaiCompatible"
    data:
      - name: provider1
        url: https://api.provider1.com
        models:
          - model1_provider1
          - model2_provider1
        api_keys:
          - your_api_key_here
          - your_api_key_here_2
  - provider: siliconflow  # "openai"  "siliconflow" "openaiCompatible"
    data:
      - name: provider1
        url: https://api.provider1.com
        models:
        api_keys:
          - your_api_key_here
          - your_api_key_here_2
          - your_api_key_here_2
          - your_api_key_here_2
          - your_api_key_here_2
          - your_api_key_here_2
          - your_api_key_here_2